import type { ConjugaisonVerb, VerbGroup } from "./types";

export const ALL_VERBS: ConjugaisonVerb[] = [
  // --- 1er groupe (-er) ---
  {
    infinitive: "chanter",
    group: "1er",
    futureRoot: "chanter",
    conjugations: {
      je: "chanterai",
      tu: "chanteras",
      "il/elle/on": "chantera",
      nous: "chanterons",
      vous: "chanterez",
      "ils/elles": "chanteront",
    },
    translation: "cantar",
    futureTranslations: {
      je: "yo cantaré",
      tu: "tú cantarás",
      "il/elle/on": "él/ella cantará",
      nous: "nosotros cantaremos",
      vous: "vosotros cantaréis",
      "ils/elles": "ellos/ellas cantarán",
    },
  },
  {
    infinitive: "jouer",
    group: "1er",
    futureRoot: "jouer",
    conjugations: {
      je: "jouerai",
      tu: "joueras",
      "il/elle/on": "jouera",
      nous: "jouerons",
      vous: "jouerez",
      "ils/elles": "joueront",
    },
    translation: "jugar",
    futureTranslations: {
      je: "yo jugaré",
      tu: "tú jugarás",
      "il/elle/on": "él/ella jugará",
      nous: "nosotros jugaremos",
      vous: "vosotros jugaréis",
      "ils/elles": "ellos/ellas jugarán",
    },
  },
  {
    infinitive: "marcher",
    group: "1er",
    futureRoot: "marcher",
    conjugations: {
      je: "marcherai",
      tu: "marcheras",
      "il/elle/on": "marchera",
      nous: "marcherons",
      vous: "marcherez",
      "ils/elles": "marcheront",
    },
    translation: "caminar",
    futureTranslations: {
      je: "yo caminaré",
      tu: "tú caminarás",
      "il/elle/on": "él/ella caminará",
      nous: "nosotros caminaremos",
      vous: "vosotros caminaréis",
      "ils/elles": "ellos/ellas caminarán",
    },
  },
  {
    infinitive: "briller",
    group: "1er",
    futureRoot: "briller",
    conjugations: {
      je: "brillerai",
      tu: "brilleras",
      "il/elle/on": "brillera",
      nous: "brillerons",
      vous: "brillerez",
      "ils/elles": "brilleront",
    },
    translation: "brillar",
    futureTranslations: {
      je: "yo brillaré",
      tu: "tú brillarás",
      "il/elle/on": "él/ella brillará",
      nous: "nosotros brillaremos",
      vous: "vosotros brillaréis",
      "ils/elles": "ellos/ellas brillarán",
    },
  },
  {
    infinitive: "rentrer",
    group: "1er",
    futureRoot: "rentrer",
    conjugations: {
      je: "rentrerai",
      tu: "rentreras",
      "il/elle/on": "rentrera",
      nous: "rentrerons",
      vous: "rentrerez",
      "ils/elles": "rentreront",
    },
    translation: "volver",
    futureTranslations: {
      je: "yo volveré",
      tu: "tú volverás",
      "il/elle/on": "él/ella volverá",
      nous: "nosotros volveremos",
      vous: "vosotros volveréis",
      "ils/elles": "ellos/ellas volverán",
    },
  },

  // --- 2ème groupe (-ir, conjugación en -iss-) ---
  {
    infinitive: "finir",
    group: "2eme",
    futureRoot: "finir",
    conjugations: {
      je: "finirai",
      tu: "finiras",
      "il/elle/on": "finira",
      nous: "finirons",
      vous: "finirez",
      "ils/elles": "finiront",
    },
    translation: "terminar",
    futureTranslations: {
      je: "yo terminaré",
      tu: "tú terminarás",
      "il/elle/on": "él/ella terminará",
      nous: "nosotros terminaremos",
      vous: "vosotros terminaréis",
      "ils/elles": "ellos/ellas terminarán",
    },
  },
  {
    infinitive: "choisir",
    group: "2eme",
    futureRoot: "choisir",
    conjugations: {
      je: "choisirai",
      tu: "choisiras",
      "il/elle/on": "choisira",
      nous: "choisirons",
      vous: "choisirez",
      "ils/elles": "choisiront",
    },
    translation: "elegir",
    futureTranslations: {
      je: "yo elegiré",
      tu: "tú elegirás",
      "il/elle/on": "él/ella elegirá",
      nous: "nosotros elegiremos",
      vous: "vosotros elegiréis",
      "ils/elles": "ellos/ellas elegirán",
    },
  },
  {
    infinitive: "réussir",
    group: "2eme",
    futureRoot: "réussir",
    conjugations: {
      je: "réussirai",
      tu: "réussiras",
      "il/elle/on": "réussira",
      nous: "réussirons",
      vous: "réussirez",
      "ils/elles": "réussiront",
    },
    translation: "lograr",
    futureTranslations: {
      je: "yo lograré",
      tu: "tú lograrás",
      "il/elle/on": "él/ella logrará",
      nous: "nosotros lograremos",
      vous: "vosotros lograréis",
      "ils/elles": "ellos/ellas lograrán",
    },
  },
  {
    infinitive: "remplir",
    group: "2eme",
    futureRoot: "remplir",
    conjugations: {
      je: "remplirai",
      tu: "rempliras",
      "il/elle/on": "remplira",
      nous: "remplirons",
      vous: "remplirez",
      "ils/elles": "rempliront",
    },
    translation: "llenar",
    futureTranslations: {
      je: "yo llenaré",
      tu: "tú llenarás",
      "il/elle/on": "él/ella llenará",
      nous: "nosotros llenaremos",
      vous: "vosotros llenaréis",
      "ils/elles": "ellos/ellas llenarán",
    },
  },

  // --- 3ème groupe (partir) ---
  {
    infinitive: "partir",
    group: "3eme",
    futureRoot: "partir",
    conjugations: {
      je: "partirai",
      tu: "partiras",
      "il/elle/on": "partira",
      nous: "partirons",
      vous: "partirez",
      "ils/elles": "partiront",
    },
    translation: "salir / irse",
    futureTranslations: {
      je: "yo me iré",
      tu: "tú te irás",
      "il/elle/on": "él/ella se irá",
      nous: "nosotros nos iremos",
      vous: "vosotros os iréis",
      "ils/elles": "ellos/ellas se irán",
    },
  },

  // --- Irregulares ---
  {
    infinitive: "aller",
    group: "irregulier",
    futureRoot: "ir",
    conjugations: {
      je: "irai",
      tu: "iras",
      "il/elle/on": "ira",
      nous: "irons",
      vous: "irez",
      "ils/elles": "iront",
    },
    translation: "ir",
    futureTranslations: {
      je: "yo iré",
      tu: "tú irás",
      "il/elle/on": "él/ella irá",
      nous: "nosotros iremos",
      vous: "vosotros iréis",
      "ils/elles": "ellos/ellas irán",
    },
  },
  {
    infinitive: "faire",
    group: "irregulier",
    futureRoot: "fer",
    conjugations: {
      je: "ferai",
      tu: "feras",
      "il/elle/on": "fera",
      nous: "ferons",
      vous: "ferez",
      "ils/elles": "feront",
    },
    translation: "hacer",
    futureTranslations: {
      je: "yo haré",
      tu: "tú harás",
      "il/elle/on": "él/ella hará",
      nous: "nosotros haremos",
      vous: "vosotros haréis",
      "ils/elles": "ellos/ellas harán",
    },
  },
  {
    infinitive: "venir",
    group: "irregulier",
    futureRoot: "viendr",
    conjugations: {
      je: "viendrai",
      tu: "viendras",
      "il/elle/on": "viendra",
      nous: "viendrons",
      vous: "viendrez",
      "ils/elles": "viendront",
    },
    translation: "venir",
    futureTranslations: {
      je: "yo vendré",
      tu: "tú vendrás",
      "il/elle/on": "él/ella vendrá",
      nous: "nosotros vendremos",
      vous: "vosotros vendréis",
      "ils/elles": "ellos/ellas vendrán",
    },
  },
  {
    infinitive: "voir",
    group: "irregulier",
    futureRoot: "verr",
    conjugations: {
      je: "verrai",
      tu: "verras",
      "il/elle/on": "verra",
      nous: "verrons",
      vous: "verrez",
      "ils/elles": "verront",
    },
    translation: "ver",
    futureTranslations: {
      je: "yo veré",
      tu: "tú verás",
      "il/elle/on": "él/ella verá",
      nous: "nosotros veremos",
      vous: "vosotros veréis",
      "ils/elles": "ellos/ellas verán",
    },
  },
  {
    infinitive: "avoir",
    group: "irregulier",
    futureRoot: "aur",
    conjugations: {
      je: "aurai",
      tu: "auras",
      "il/elle/on": "aura",
      nous: "aurons",
      vous: "aurez",
      "ils/elles": "auront",
    },
    translation: "tener",
    futureTranslations: {
      je: "yo tendré",
      tu: "tú tendrás",
      "il/elle/on": "él/ella tendrá",
      nous: "nosotros tendremos",
      vous: "vosotros tendréis",
      "ils/elles": "ellos/ellas tendrán",
    },
  },
  {
    infinitive: "être",
    group: "irregulier",
    futureRoot: "ser",
    conjugations: {
      je: "serai",
      tu: "seras",
      "il/elle/on": "sera",
      nous: "serons",
      vous: "serez",
      "ils/elles": "seront",
    },
    translation: "ser / estar",
    futureTranslations: {
      je: "yo seré",
      tu: "tú serás",
      "il/elle/on": "él/ella será",
      nous: "nosotros seremos",
      vous: "vosotros seréis",
      "ils/elles": "ellos/ellas serán",
    },
  },
];

export const VERBS_BY_GROUP: Record<VerbGroup, ConjugaisonVerb[]> = {
  "1er": ALL_VERBS.filter((v) => v.group === "1er"),
  "2eme": ALL_VERBS.filter((v) => v.group === "2eme"),
  "3eme": ALL_VERBS.filter((v) => v.group === "3eme"),
  irregulier: ALL_VERBS.filter((v) => v.group === "irregulier"),
};

export function getVerbsByGroups(groups: VerbGroup[]): ConjugaisonVerb[] {
  return ALL_VERBS.filter((v) => groups.includes(v.group));
}
